from dataclasses import dataclass
from typing import Optional

@dataclass
class LLMResponse:
    """
    A structured container for the response from the LLM.

    Attributes:
        answer (str): The direct answer extracted or generated by the LLM.
        source_chunk_text (str): The text of the source chunk used to generate the answer.
        page_number (Optional[int]): The page number where the source chunk is located.
        section_number (Optional[str]): The section number of the source chunk.
    """
    answer: str
    source_chunk_text: Optional[str] = None
    page_number: Optional[int] = None
    section_number: Optional[str] = None